export const GET_DATA = 'GET_DATA';
export const GET_DATA_DEFAIL = 'GET_DATA_DEFAIL';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const CHANGE_HEART_FOOD = 'CHANGE_HEART_FOOD';
export const CHANGE_HEART_FOOD_DEFAIL = 'CHANGE_HEART_FOOD_DEFAIL';
export const CHANGE_HEART_FOOD_SUCCESS = 'CHANGE_HEART_FOOD_SUCCESS';
