export const GET_DATA = 'GET_DATA';
export const GET_DATA_DEFAIL = 'GET_DATA_DEFAIL';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const CHANGE_HEART_FOOD = 'CHANGE_HEART_FOOD';
export const CHANGE_HEART_FOOD_DEFAIL = 'CHANGE_HEART_FOOD_DEFAIL';
export const CHANGE_HEART_FOOD_SUCCESS = 'CHANGE_HEART_FOOD_SUCCESS';

export const CHOSSE_OUT_STANDING_FOOD = 'CHOSSE_OUT_STANDING_FOOD';
export const CHOSSE_OUT_STANDING_FOOD_DEFAIL =
  'CHOSSE_OUT_STANDING_FOOD_DEFAIL';
export const CHOSSE_OUT_STANDING_FOOD_SUCCESS =
  'CHOSSE_OUT_STANDING_FOOD_SUCCESS';

export const DELETE_FOOD_MY_CART = 'DELETE_FOOD_MY_CART';
export const DELETE_FOOD_MY_CART_DEFAIL = 'DELETE_FOOD_MY_CART_DEFAIL';
export const DELETE_FOOD_MY_CART_SUCCESS = 'DELETE_FOOD_MY_CART_SUCCESS';

export const LIST_ORDER = 'LIST_ORDER';
export const LIST_ORDER_DEFAIL = 'LIST_ORDER_DEFAIL';
export const LIST_ORDER_SUCCESS = 'LIST_ORDER_SUCCESS';

export const ADD_FOOD_ORDER = 'ADD_FOOD_ORDER';
export const REMOVE_FOOD_ORDER = 'REMOVE_FOOD_ORDER';
export const ORDER_FOOD = 'ORDER_FOOD';
