export const data: any = {
  error: false,
  loading: true,
  listData: [],
  myCart: [],
  listOrder: [],
  data: {
    foodList: [
      {
        name: 'Hamburger',
        icon: 'https://vi.seaicons.com/wp-content/uploads/2017/03/hamburger-icon-3.png',
        categoryFood: 'hamburger',
      },
      {
        name: 'Pizza',
        icon: 'https://vi.seaicons.com/wp-content/uploads/2017/03/pizza-slice-icon.png',
        categoryFood: 'pizza',
      },
      {
        name: 'Phở bò',
        icon: 'https://www.pho24.com.vn/wp-content/uploads/2018/05/600x328px_MENU_SLIDE-BIG-PHO_MELAMIN-01.png',
        categoryFood: 'noodles',
      },
      {
        name: 'Thịt quay',
        icon: 'https://genshin.honeyhunterworld.com/img/i_1102_3.webp',
        categoryFood: 'meat',
      },
      {
        name: 'Rau xanh',
        icon: 'https://cdn.pixabay.com/photo/2014/12/22/00/05/green-576756_1280.png',
        categoryFood: 'vegetable',
      },
      {
        name: 'Bánh kem',
        icon: 'https://findicons.com/files/icons/346/sweet/128/cake2.png',
        categoryFood: 'cake',
      },
      {
        name: 'Bia',
        icon: 'https://vi.seaicons.com/wp-content/uploads/2017/03/beer-icon.png',
        categoryFood: 'bear',
      },
      {
        name: 'Khác',
        icon: 'https://cdn-icons-png.flaticon.com/512/254/254032.png',
        categoryFood: 'more',
      },
    ],
    outstandingFood: [
      {
        name: 'Phở bò',
        img: 'https://cachnau.vn/wp-content/uploads/2021/11/cach-nau-pho-bo-nam-dinh.jpg',
        distance: '1.5km',
        assess: '4.8',
        reviewCount: '1.2k',
        price: '30k vnđ',
        shippingCost: '5k vnđ',
        isHeart: false,
      },
      {
        name: 'Bánh mì',
        img: 'https://banhmipho.vn/wp-content/uploads/2021/08/vuong.jpg-602x470.png',
        distance: '1.5km',
        assess: '4.9',
        reviewCount: '3.9k',
        price: '15k vnđ',
        shippingCost: '5k vnđ',
        isHeart: false,
      },
      {
        name: 'Cơm tấm',
        img: 'https://statics.vinpearl.com/com-tam-ngon-o-sai-gon-0_1630562640.jpg',
        distance: '5.5km',
        assess: '4.2',
        reviewCount: '1.1k',
        price: '60k vnđ',
        shippingCost: '8k vnđ',
        isHeart: false,
      },
      {
        name: 'Nem quận',
        img: 'https://cdn.tgdd.vn/2020/09/CookRecipe/Avatar/goi-cuon-thap-cam-thumbnail.jpg',
        distance: '2.5km',
        assess: '3.9',
        reviewCount: '300',
        price: '40k vnđ',
        shippingCost: '5k vnđ',
        isHeart: false,
      },
    ],
  },
  listDataOutStandingFood: [],
};
